export const refs = {
  movie: document.querySelector('.movie'),
  refHeader: document.querySelector('.header'),
  // myLibraryBtn: document.querySelector('.js-library'),
  refSearchForm: document.querySelector('.js-searchForm'),
  refBtnGroup: document.querySelector('.btn-groupList'),
  homePageHome: document.querySelector('.nav__list-text'),
  // homePageLogo: document.querySelector('.logo'),
  input: document.querySelector('.search-form'),
  moviePogination: document.querySelector('.movie-pogination'),
  movieImage: document.querySelector('.modal__img'),
  movieTitle: document.querySelector('.modal__film-title'),
  movieVoteOrange: document.querySelector('.modal-vote--orange'),
  movieVoteGrey: document.querySelector('.modal-vote--grey'),
  moviePopularity: document.querySelector('.modal-short-info__description-item--popularity'),
  movieOriginalTitle: document.querySelector('.modal-short-info__description-item--original-title'),
  movieGanre: document.querySelector('.modal-short-info__description-item--ganre'),
  movieOverview: document.querySelector('.modal__about-text'),
  movieWatched: document.querySelector('.card__btn-watched'),
  movieQueue: document.querySelector('.js-queue'),
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modal: document.querySelector('.backdrop'),
  body: document.querySelector('body'),
  backdrop: document.querySelector('.backdrop'),
  movieModal: document.querySelector('.movie-modal-id'),
  btnHome: document.querySelector('.js-heder-home'),
  btnLibrary: document.querySelector('.js-library'),
  btnLogo: document.querySelector('.logo'),
  searchInput: document.querySelector('.search__input'),
  // header
  btnWathed: document.querySelector('.js-wathed-header'),
  btnQueue: document.querySelector('.js-queue-header'),
  // modal
  btnAddWatched: document.querySelector('.js-watched'),
  btnAddQueue: document.querySelector('.js-queue'),
  library: document.querySelector('.nav__list-text--home'),
  movieTrailer: document.querySelector('.js-modal-trailer'),
  // modal2
  backdrop2: document.querySelector('.backdrop2'),
  closeModalBtn2: document.querySelector('.modal-close-btn2'),
  player: document.querySelector('#player'),
  // lang
  btnLang: document.querySelector('.user_profile_lang'),
  langEn: document.querySelector('.lang-en'),
  langRu: document.querySelector('.lang-ru'),
  langUk: document.querySelector('.lang-uk'),
  // modal lang
  vote: document.querySelector('.js-lang-vote'),
  popularity: document.querySelector('.js-lang-popularity'),
  title: document.querySelector('.js-lang-title'),
  genre: document.querySelector('.js-lang-genre'),
  trailer: document.querySelector('.js-lang-trailer'),
  about: document.querySelector('.js-lang-about'),
  //
};
